# This configuration is intended for development purpose, it's your responsibility to harden it for production
name: mynhipsterapp

services:
  postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=myNhipsterApp
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d myNhipsterApp']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5432:5432
